In [1]:
music = '1p2p(17)0p'

In [2]:
dir(music)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [10]:
positions = []

pos = None
cat = None
is_year = False
for c in music:
    if c == '(':
        is_year = True
        continue
        
    if c == ')':
        is_year = False
        continue
        
    if is_year: continue
        
    if pos is None:
        pos = c
        cat = None
        positions.append(pos)
        continue
    
    if cat is None:
        cat = c
        pos = None
        continue
        
positions
        

['1', '2', '0']

In [11]:
import numpy as np

In [12]:
np.empty(2)

array([ 0.00000000e+000, -1.33602965e-315])

In [13]:
np.zeros(2)

array([0., 0.])

In [16]:
a = np.zeros(2)
a.fill(np.nan)
a

array([nan, nan])